### ISSUE TITLE
destroyAttachments() returns nothing

### ISSUE THREAD

**Issue by Skeeve2** [tts-community/api#39]
https://tts-community.github.io/api/object/#action-function

There doesn't seem to be an icon for destroyAttachments(), does it return nothing?

**Comment by omniraptorr** [comment]
the relevant line is https://github.com/tts-community/api/blame/master/docs/object.md#L184 but i don't see anything different that would cause the ::after part of the css rule not to render for that span.

**Comment by Eldinnie** [comment]
That actual line is:
https://github.com/tts-community/api/blame/master/docs/object.md#L186-L187
The porblem is the stap is `ret bool` in stead of `ret boo` 
Who though three leter coeds was a good idea :D
